# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'Install dependencies'
  inputs:
    workingDir: $(System.DefaultWorkingDirectory)
    command: 'ci'

- task: Npm@1
  displayName: 'Tests'
  inputs:
    workingDir: $(System.DefaultWorkingDirectory)
    command: 'custom'
    customCommand: 'run test'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish coverage'
  condition: succeededOrFailed()
  inputs:
    workingDir: $(System.DefaultWorkingDirectory)
    failIfCoverageEmpty: true
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'coverage/cobertura-coverage.xml'

- task: PublishTestResults@2
  displayName: 'Publish test results'
  condition: succeededOrFailed()
  inputs:
    workingDir: $(System.DefaultWorkingDirectory)
    testResultsFiles: 'junit.xml'

- task: Npm@1
  displayName: 'Build'
  inputs:
    command: 'custom'
    workingDir: $(System.DefaultWorkingDirectory)
    customCommand: 'run build'   

- task: Npm@1
  displayName: Remove extraneous packages
  inputs:
    command: custom
    workingDir: $(System.DefaultWorkingDirectory)
    verbose: false
    customCommand: prune --production     

- task: ArchiveFiles@2
  displayName: Archive files
  inputs:
    rootFolderOrFile: $(System.DefaultWorkingDirectory)
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
